"""Canonical deterministic citation snapshot for the research monograph."""

from .compilation import ResearchMonographCitationSnapshotCompiler
from .records import (
    CitationContentAlgorithm,
    CitationContentIdentity,
    CitationSnapshotError,
    CitationSnapshotErrorCode,
    ManuscriptBibliographyEntrySnapshot,
    ManuscriptCitationCall,
    ManuscriptCitationCommandKind,
    ManuscriptCitationGroup,
    ManuscriptCitationOccurrence,
    ManuscriptCitationOrigin,
    ManuscriptCitationPriority,
    ManuscriptCitationSnapshot,
    ManuscriptCitationSourceGap,
    ManuscriptCitationSourceGapReason,
    ManuscriptCitationTodo,
    ManuscriptIncludeInstance,
    ManuscriptSourceFileSnapshot,
    ManuscriptSourceLocator,
    ResearchMonographCitationSnapshotRequest,
    ResearchMonographCitationSnapshotResult,
)

__all__ = [
    "CitationContentAlgorithm",
    "CitationContentIdentity",
    "CitationSnapshotError",
    "CitationSnapshotErrorCode",
    "ManuscriptBibliographyEntrySnapshot",
    "ManuscriptCitationCall",
    "ManuscriptCitationCommandKind",
    "ManuscriptCitationGroup",
    "ManuscriptCitationOccurrence",
    "ManuscriptCitationOrigin",
    "ManuscriptCitationPriority",
    "ManuscriptCitationSnapshot",
    "ManuscriptCitationSourceGap",
    "ManuscriptCitationSourceGapReason",
    "ManuscriptCitationTodo",
    "ManuscriptIncludeInstance",
    "ManuscriptSourceFileSnapshot",
    "ManuscriptSourceLocator",
    "ResearchMonographCitationSnapshotCompiler",
    "ResearchMonographCitationSnapshotRequest",
    "ResearchMonographCitationSnapshotResult",
]
