"""Bounded evidence-grounded publication-authoring contracts.

The package exposes immutable in-memory records, one structural local-inference port,
and one stateless proposal composer. It performs no retrieval, ranking, shell,
database, browser, remote-network, manuscript, bibliography, or publication action.
Its concrete inference adapter contacts only a fixed-model Ollama service on literal
IPv4 loopback, and its bounded retention owner writes only mode-0600 ignored-cache
response observability artifacts.
"""

from .authoring import (
    AdHocEvidenceRetrievalProjection,
    AuthorSuppliedPublisherAbstractAdapter,
    AuthorSuppliedPublisherAbstractEvidence,
    CitationKeyStatus,
    EvidenceGroundedManuscriptAuthor,
    EvidenceProvenanceStatus,
    EvidenceRetrievalOutcomeProjection,
    EvidenceRetrievalProjection,
    EvidenceSourceScope,
    HumanAcceptanceStatus,
    LocalManuscriptInferencePort,
    ManuscriptAuthoringIssue,
    ManuscriptAuthoringOutcome,
    ManuscriptAuthoringRequest,
    ManuscriptAuthoringResult,
    ManuscriptInferenceRequest,
    ManuscriptInferenceResponse,
    ManuscriptProposal,
    ManuscriptTargetContext,
    OllamaLoopbackManuscriptInferenceAdapter,
    OllamaRawResponseArtifact,
    OllamaResponseRetention,
    ProjectedCitationIdentity,
    ProjectKoiosIngestionAdapter,
    ProjectKoiosReferencesAdapter,
    ProjectKoiosSearchAdapter,
    ProposedCitation,
    ProposedEvidenceMarker,
    RetainedLocalManuscriptAuthoringRun,
    RetrievedEvidenceExcerpt,
    TranscriptEvidenceMappingBasis,
    TranscriptEvidenceSelectionOutcomeProjection,
    TranscriptEvidenceSelectionReference,
)

__all__ = (
    "AdHocEvidenceRetrievalProjection",
    "AuthorSuppliedPublisherAbstractAdapter",
    "AuthorSuppliedPublisherAbstractEvidence",
    "CitationKeyStatus",
    "EvidenceGroundedManuscriptAuthor",
    "EvidenceProvenanceStatus",
    "EvidenceRetrievalOutcomeProjection",
    "EvidenceRetrievalProjection",
    "EvidenceSourceScope",
    "HumanAcceptanceStatus",
    "LocalManuscriptInferencePort",
    "ManuscriptAuthoringIssue",
    "ManuscriptAuthoringOutcome",
    "ManuscriptAuthoringRequest",
    "ManuscriptAuthoringResult",
    "ManuscriptInferenceRequest",
    "ManuscriptInferenceResponse",
    "ManuscriptProposal",
    "ManuscriptTargetContext",
    "OllamaLoopbackManuscriptInferenceAdapter",
    "OllamaRawResponseArtifact",
    "OllamaResponseRetention",
    "ProjectedCitationIdentity",
    "ProjectKoiosIngestionAdapter",
    "ProjectKoiosReferencesAdapter",
    "ProjectKoiosSearchAdapter",
    "ProposedCitation",
    "ProposedEvidenceMarker",
    "RetainedLocalManuscriptAuthoringRun",
    "RetrievedEvidenceExcerpt",
    "TranscriptEvidenceMappingBasis",
    "TranscriptEvidenceSelectionOutcomeProjection",
    "TranscriptEvidenceSelectionReference",
)
