"""Public calculator-independent scientific Workflow contracts.

The root namespace exports immutable scientific Task, Workflow, gate, activation,
composition, artifact-provenance, and effect-free colored-Petri-net adaptation
contracts.  Generic colored-Petri-net objects remain public from
:mod:`ksdft2effmass.petrinet.colored`. The former abbreviated
``ksdft2effmass.workflows.cpn`` compatibility package is retired and is not aliased
from this namespace.
"""

from .artifacts import (
    ArtifactContentIdentity,
    ArtifactIdentity,
    ArtifactLineageKind,
    ArtifactLineageRelation,
    ArtifactLineageRelationIdentity,
    ArtifactLineageSourceIdentity,
    ArtifactManifest,
    ArtifactManifestEntry,
    ArtifactManifestEntryIdentity,
    ArtifactManifestIdentity,
    ArtifactManifestSupersessionIdentity,
    ArtifactProducerKind,
    ArtifactProducerProvenance,
    ArtifactProducerProvenanceIdentity,
    ExternalSourceObservation,
    HumanAuthoredCompactInput,
    ImportedRetainedFixture,
    RepresentedWorkflowProducer,
    ResultArtifactRelationIdentity,
    UnknownLegacyProducer,
)
from .cpn_adapter import (
    ColoredPetriNetWorkflowActivationFailureCode,
    ColoredPetriNetWorkflowActivationMode,
    ColoredPetriNetWorkflowActivationOutcomeKind,
    ColoredPetriNetWorkflowActivationRequest,
    ColoredPetriNetWorkflowActivationResult,
    ColoredPetriNetWorkflowActivationResultIdentity,
    ColoredPetriNetWorkflowAdapter,
    ColoredPetriNetWorkflowMapping,
    ColoredPetriNetWorkflowSelectionPolicy,
    WorkflowResultTokenMapping,
)
from .model import (
    AllOfTaskActivationSelection,
    AnyOfTaskActivationSelection,
    AttemptIdentity,
    DirectTaskActivationSelection,
    OperationIdentity,
    ResultObject,
    ResultObjectIdentity,
    Task,
    TaskActivation,
    TaskActivationIdentity,
    TaskActivationSelection,
    TaskDefinitionIdentity,
    TaskExecutionContext,
    TaskGateSelection,
    TaskInputBinding,
    TaskInstance,
    TaskInstanceIdentity,
    TaskStartGate,
    TaskStartGateIdentity,
    TaskStartGateSet,
    TaskStartGateSetIdentity,
    TaskStartGateSetMode,
    Workflow,
    WorkflowComposition,
    WorkflowIdentity,
    WorkflowRunIdentity,
)

__all__ = [
    "AllOfTaskActivationSelection",
    "ArtifactContentIdentity",
    "ArtifactIdentity",
    "ArtifactLineageKind",
    "ArtifactLineageRelation",
    "ArtifactLineageRelationIdentity",
    "ArtifactLineageSourceIdentity",
    "ArtifactManifest",
    "ArtifactManifestEntry",
    "ArtifactManifestEntryIdentity",
    "ArtifactManifestIdentity",
    "ArtifactManifestSupersessionIdentity",
    "ArtifactProducerKind",
    "ArtifactProducerProvenance",
    "ArtifactProducerProvenanceIdentity",
    "AnyOfTaskActivationSelection",
    "AttemptIdentity",
    "ColoredPetriNetWorkflowActivationFailureCode",
    "ColoredPetriNetWorkflowActivationMode",
    "ColoredPetriNetWorkflowActivationOutcomeKind",
    "ColoredPetriNetWorkflowActivationRequest",
    "ColoredPetriNetWorkflowActivationResult",
    "ColoredPetriNetWorkflowActivationResultIdentity",
    "ColoredPetriNetWorkflowAdapter",
    "ColoredPetriNetWorkflowMapping",
    "ColoredPetriNetWorkflowSelectionPolicy",
    "DirectTaskActivationSelection",
    "ExternalSourceObservation",
    "HumanAuthoredCompactInput",
    "ImportedRetainedFixture",
    "OperationIdentity",
    "RepresentedWorkflowProducer",
    "ResultArtifactRelationIdentity",
    "ResultObject",
    "ResultObjectIdentity",
    "Task",
    "TaskActivation",
    "TaskActivationIdentity",
    "TaskActivationSelection",
    "TaskDefinitionIdentity",
    "TaskExecutionContext",
    "TaskGateSelection",
    "TaskInputBinding",
    "TaskInstance",
    "TaskInstanceIdentity",
    "TaskStartGate",
    "TaskStartGateIdentity",
    "TaskStartGateSet",
    "TaskStartGateSetIdentity",
    "TaskStartGateSetMode",
    "UnknownLegacyProducer",
    "Workflow",
    "WorkflowComposition",
    "WorkflowIdentity",
    "WorkflowResultTokenMapping",
    "WorkflowRunIdentity",
]
