"""Public calculator-independent scientific Workflow contracts.

The root namespace exports immutable scientific Task, Workflow, gate, activation,
composition, and effect-free colored-Petri-net adaptation contracts.  Generic
colored-Petri-net objects remain public from :mod:`ksdft2effmass.petrinet.colored`;
the supported v1 compatibility API remains under
:mod:`ksdft2effmass.workflows.cpn`.
"""

from .cpn_adapter import (
    ColoredPetriNetWorkflowActivationFailureCode,
    ColoredPetriNetWorkflowActivationMode,
    ColoredPetriNetWorkflowActivationOutcomeKind,
    ColoredPetriNetWorkflowActivationRequest,
    ColoredPetriNetWorkflowActivationResult,
    ColoredPetriNetWorkflowActivationResultIdentity,
    ColoredPetriNetWorkflowAdapter,
    ColoredPetriNetWorkflowMapping,
    ColoredPetriNetWorkflowSelectionPolicy,
    WorkflowResultTokenMapping,
)
from .model import (
    AllOfTaskActivationSelection,
    AnyOfTaskActivationSelection,
    AttemptIdentity,
    DirectTaskActivationSelection,
    OperationIdentity,
    ResultObject,
    ResultObjectIdentity,
    Task,
    TaskActivation,
    TaskActivationIdentity,
    TaskActivationSelection,
    TaskDefinitionIdentity,
    TaskExecutionContext,
    TaskGateSelection,
    TaskInputBinding,
    TaskInstance,
    TaskInstanceIdentity,
    TaskStartGate,
    TaskStartGateIdentity,
    TaskStartGateSet,
    TaskStartGateSetIdentity,
    TaskStartGateSetMode,
    Workflow,
    WorkflowComposition,
    WorkflowIdentity,
    WorkflowRunIdentity,
)

__all__ = [
    "AllOfTaskActivationSelection",
    "AnyOfTaskActivationSelection",
    "AttemptIdentity",
    "ColoredPetriNetWorkflowActivationFailureCode",
    "ColoredPetriNetWorkflowActivationMode",
    "ColoredPetriNetWorkflowActivationOutcomeKind",
    "ColoredPetriNetWorkflowActivationRequest",
    "ColoredPetriNetWorkflowActivationResult",
    "ColoredPetriNetWorkflowActivationResultIdentity",
    "ColoredPetriNetWorkflowAdapter",
    "ColoredPetriNetWorkflowMapping",
    "ColoredPetriNetWorkflowSelectionPolicy",
    "DirectTaskActivationSelection",
    "OperationIdentity",
    "ResultObject",
    "ResultObjectIdentity",
    "Task",
    "TaskActivation",
    "TaskActivationIdentity",
    "TaskActivationSelection",
    "TaskDefinitionIdentity",
    "TaskExecutionContext",
    "TaskGateSelection",
    "TaskInputBinding",
    "TaskInstance",
    "TaskInstanceIdentity",
    "TaskStartGate",
    "TaskStartGateIdentity",
    "TaskStartGateSet",
    "TaskStartGateSetIdentity",
    "TaskStartGateSetMode",
    "Workflow",
    "WorkflowComposition",
    "WorkflowIdentity",
    "WorkflowResultTokenMapping",
    "WorkflowRunIdentity",
]
