"""Deprecated compatibility façade for periodic two-dimensional campaigns."""

import warnings

from ...periodic2d import (
    Periodic2DCommonSpaceComparisonRequest,
    Periodic2DCommonSpaceComparisonResult,
    Periodic2DCommonSpaceOperatorComparator,
    Periodic2DCompositeCampaign,
    Periodic2DCompositeCampaignModel,
    Periodic2DDefect,
    Periodic2DDefectExtractionRequest,
    Periodic2DDefectExtractionResult,
    Periodic2DDefectLocalityAnalyzer,
    Periodic2DDefectLocalityRequest,
    Periodic2DDefectLocalityResult,
    Periodic2DDefectModel,
    Periodic2DDefectPerturbationExtractor,
    Periodic2DDefectRepresentationRequest,
    Periodic2DDefectRepresentationResult,
    Periodic2DDefectRepresenter,
    Periodic2DIsolatedBandCampaign,
    Periodic2DIsolatedBandCampaignModel,
    Periodic2DOptimizerBasinCampaign,
    Periodic2DOptimizerBasinCampaignModel,
    Periodic2DOptimizerReanalysisCampaign,
    Periodic2DOptimizerReanalysisCampaignModel,
    Periodic2DOptimizerRegressionCampaign,
    Periodic2DOptimizerRegressionCampaignModel,
    Periodic2DOptimizerStandaloneCampaign,
    Periodic2DOptimizerStandaloneCampaignModel,
    Periodic2DTopologicalCampaign,
    Periodic2DTopologicalCampaignModel,
    Periodic2DTopologicalPhaseSweepCampaign,
    Periodic2DTopologicalPhaseSweepCampaignModel,
    Periodic2DWannier90BalancedCampaign,
    Periodic2DWannier90BalancedCampaignModel,
    Periodic2DWannier90StudyCampaign,
    Periodic2DWannier90StudyCampaignModel,
)

warnings.warn(
    "ksdft2effmass.campaigns.research_monograph.periodic2d is deprecated; "
    "import ksdft2effmass.campaigns.periodic2d instead",
    DeprecationWarning,
    stacklevel=2,
)

__all__ = [
    "Periodic2DCommonSpaceComparisonRequest",
    "Periodic2DCommonSpaceComparisonResult",
    "Periodic2DCommonSpaceOperatorComparator",
    "Periodic2DDefect",
    "Periodic2DDefectExtractionRequest",
    "Periodic2DDefectExtractionResult",
    "Periodic2DDefectLocalityAnalyzer",
    "Periodic2DDefectLocalityRequest",
    "Periodic2DDefectLocalityResult",
    "Periodic2DDefectModel",
    "Periodic2DDefectPerturbationExtractor",
    "Periodic2DDefectRepresentationRequest",
    "Periodic2DDefectRepresentationResult",
    "Periodic2DDefectRepresenter",
    "Periodic2DCompositeCampaign",
    "Periodic2DCompositeCampaignModel",
    "Periodic2DIsolatedBandCampaign",
    "Periodic2DIsolatedBandCampaignModel",
    "Periodic2DOptimizerBasinCampaign",
    "Periodic2DOptimizerBasinCampaignModel",
    "Periodic2DOptimizerReanalysisCampaign",
    "Periodic2DOptimizerReanalysisCampaignModel",
    "Periodic2DOptimizerRegressionCampaign",
    "Periodic2DOptimizerRegressionCampaignModel",
    "Periodic2DOptimizerStandaloneCampaign",
    "Periodic2DOptimizerStandaloneCampaignModel",
    "Periodic2DTopologicalCampaign",
    "Periodic2DTopologicalCampaignModel",
    "Periodic2DTopologicalPhaseSweepCampaign",
    "Periodic2DTopologicalPhaseSweepCampaignModel",
    "Periodic2DWannier90BalancedCampaign",
    "Periodic2DWannier90BalancedCampaignModel",
    "Periodic2DWannier90StudyCampaign",
    "Periodic2DWannier90StudyCampaignModel",
]
